### ISSUE TITLE
Help with VALD line list files and partition function files when calculating ion cross-sections with the 'summon' function?

### ISSUE THREAD

**Issue by MiriCaradonna** [MartianColonist/Cthulhu#29]
Hello! @zkbt and I are trying to calculate singly-ionized oxygen and hydrogen cross-sections. I started following the "Atomic and Ionic Cross Sections" tutorial, and successfully followed Part 1 where we download the line lists from VALD. VALD sent me an email for each ion with a link to a .gz file, called 'MirielleCaradonna.002742.gz' for Ca 1 and 'MirielleCaradonna.002743.gz' for Ca 2 that I extracted to get a line list file called 'MirielleCaradonna.002742' and 'MirielleCaradonna.002743', that didn't have a file type attached to it.

I tried to go on to create Ca 1 and 2 cross sections, and copied the first code block, and changed the 'VALD_data_dir' to where I had my line lists. The error I got was: 

 ----- The VALD line list for this atom/isotope combination does not exist. Please try again. -----

It seems like the 'check' function in VALD.py is looking for a file with a particular name and a .h5 type, which is not what VALD gave me. I tried changing the file name to 'Ca_I.h5' which seems like what the code is expecting. This got me one step further, but then it gave me an error saying it could not find a partition function file. 

It seems like I'm missing the step "Part 2: Processing Line Lists for use with Cthulhu". Do you have any tips on how I should proceed with this step, or if I can help with filling in the documentation?

Thank you! I'm excited about this package, and I'm looking forward to using it!

**Comment by zkbt** [comment]
Hi! To add a little more context here, @MiriCaradonna and I are trying to post-process some Martian atmospheric escape simulations to estimate what they might look like in transit. So, we're curious about atomic and ionic cross sections at absurdly low pressures, and we were excited to poke at what your lovely Cthulhu might be able to do. It might be a total non-starter, and if you have any other suggestions of where we should look for low-pressure atoms + ions, we'd be super grateful. But if we can help finish this last little bit of getting the VALD linelists to work, that'd be swell too!

**Comment by arnav-agrawal** [comment]
Hi @MiriCaradonna and @zkbt,

Thank you for using the package! The VALD line lists that you downloaded do need to be processed before being used as input files for Cthulhu. And we have the processing script for that (`process_VALD_file`) in `VALD.py`. For some reason, it must have completely slipped our minds to finish up the "Part 2: Processing Line Lists for use with Cthulhu" section. Sorry about that, and thanks for noticing our slip-up. Give us a couple days, and I think myself or @MartianColonist should be able to fill out that section with instructions on how to use `process_VALD_file` for this intermediary step. We can send a message in this thread when our instructions are done and tested. 

As far as your question on the premise of using Cthulhu to compute atomic and ionic cross-sections at absurdly low pressures, I don't see any reason that can't be done! @MartianColonist, do you see any potential problems from the science side of things?

**Comment by zkbt** [comment]
Amazing, thanks so much, @arnav-agrawal ! We'll sit tight while you so kindly finish the docs. Please let us know if there's anything @MiriCaradonna or I can do to help!

**Comment by MartianColonist** [comment]
Hi @zkbt @MiriCaradonna,

Thanks for catching this gap in our documentation! We've filled in the 'Part 2' now on the atoms and ions tutorial:
https://cthulhu.readthedocs.io/en/latest/content/notebooks/cross_section_atomic.html

Please let us know if you run into any issues with the file format conversion.

This Martian upper-atmosphere science case is pretty cool, hopefully Cthulhu can help here!

**Comment by zkbt** [comment]
Amazing, thank you! We'll take a look next week!

**Comment by MiriCaradonna** [comment]
Thank you so much for the added documentation; I was able to process the files! However, I'm running into another problem with the next step. I can't seem to find the partition function file. Should it be provided in the package when you install it, or is there a function I need to call to create it? Thank you!

**Comment by arnav-agrawal** [comment]
Yeah, we noticed that was also missing last week. It should be on the main branch if you pull the latest version. It's at the top level.

**Comment by MiriCaradonna** [comment]
Awesome, I got it, thank you!

**Comment by MiriCaradonna** [comment]
I was able to replicate your results for the Ca cross sections plot in the tutorial just now! Mission accomplished!

**Comment by MartianColonist** [comment]
Amazing! We're looking forward to seeing what you find with Cthulhu 🐙
